name: Trigger gate-way auto deployment
on:
  # 手動実行用トリガー
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repo
      uses: actions/checkout@v2

    - name: Set repository name to env
      run: | 
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
    - name: Confirm if env have REPOSITORY_NAME
      run: |
        echo ${{ env.REPOSITORY_NAME }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Maven build, clean
      run: |
        mvn clean package -DskipTests -Denv=cloud
