name: Trigger gate-way auto deployment
on:
  # 手動実行用トリガー
  workflow_dispatch:
  
  # Add a trigger
  # 自動実行用トリガー
  push:
    branches: 
      [ master ]
    paths:
    - 'spring-petclinic-api-gateway/**'

env:
  AZURE_SUBSCRIPTION: 3c2c8146-8e4d-4a49-abc9-cb35c4c23d7b
  SPRING_APPS_SERVICE: sc-petclinic-spring-apps-0628
  RESOURCE_GROUP: SPRING-APPS-RG
  # ==== APPS ====:
  API_GATEWAY: api-gateway
  # ==== JARS ====:
  API_GATEWAY_JAR: spring-petclinic-api-gateway/target/spring-petclinic-api-gateway-2.5.1.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repo
      uses: actions/checkout@v2

    - name: Set repository name to env
      run: | 
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
    - name: Confirm if env have REPOSITORY_NAME
      run: |
        echo ${{ env.REPOSITORY_NAME }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Maven build, clean
      run: |
        mvn clean package -DskipTests -Denv=cloud
        
    - name: Upload jar file
      uses: actions/upload-artifact@v3
      with:
        name: target-file
        path: ${{ github.workspace }}/${{ env.API_GATEWAY_JAR }} 

  deploy: 
    needs:
    - build
    runs-on: ubuntu-latest      
    steps:
    - name: Login with Service SP
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Get Inactive Side Name"
      id: show-inactive-side     
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az extension add --name spring
          name=$(az spring app deployment list --app ${{ env.API_GATEWAY }} -s ${{ env.SPRING_APPS_SERVICE }} -g ${{ env.RESOURCE_GROUP }} --query "[?properties.active == \`false\`].name" --output tsv)
          echo "deployment-name=$name"
          echo "deployment-name=$name" >> $GITHUB_OUTPUT

    - name: Download jar file
      id: download
      uses: actions/download-artifact@v3
      with:
        name: target-file
          
    - name: Deploy to Inactive Side
      id: deploy-to-springapps
      uses: azure/spring-apps-deploy@v1
      with:
        azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
        action: deploy
        service-name: ${{ env.SPRING_APPS_SERVICE }}
        app-name: ${{ env.API_GATEWAY }}
        deployment-name:  ${{ steps.show-inactive-side.outputs.deployment-name }}
        package: spring-petclinic-api-gateway-2.5.1.jar
        jvm-options: -Xms1024m -Xmx1024m -Dspring.profiles.active=mysql,azure

    - name: Get Endpoint
      id: get-endpoint     
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az extension add --name spring
          echo "app-url=$(az spring test-endpoint list --name ${{ env.SPRING_APPS_SERVICE }} -g ${{ env.RESOURCE_GROUP }} --app ${{ env.API_GATEWAY }} -d  ${{ steps.show-inactive-side.outputs.deployment-name }} --query "[primaryTestEndpoint]" --output tsv)" >> $GITHUB_OUTPUT      

    - name: Health check in Inactive Side
      uses: jtalk/url-health-check-action@v2
      with:
        url: ${{ steps.get-endpoint.outputs.app-url }}api/customer/owners
        follow-redirect: true
        max-attempts: 10
        retry-delay: 10s
        retry-all: true
