name: Trigger gate-way auto deployment
on:
  # 手動実行用トリガー
  workflow_dispatch:
  
  # Add a trigger
  # 自動実行用トリガー
  push:
    branches: 
      [ master ]
    paths:
    - 'spring-petclinic-api-gateway/**'

env:
  AZURE_SUBSCRIPTION: 3c2c8146-8e4d-4a49-abc9-cb35c4c23d7b
  SPRING_APPS_SERVICE: sc-petclinic-spring-apps-0628
  RESOURCE_GROUP: SPRING-APPS-RG
  # ==== APPS ====:
  API_GATEWAY: api-gateway
  # ==== JARS ====:
  API_GATEWAY_JAR: spring-petclinic-api-gateway/target/spring-petclinic-api-gateway-2.5.1.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repo
      uses: actions/checkout@v2

    - name: Set repository name to env
      run: | 
        echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
    - name: Confirm if env have REPOSITORY_NAME
      run: |
        echo ${{ env.REPOSITORY_NAME }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Maven build, clean
      run: |
        mvn clean package -DskipTests -Denv=cloud
        
    - name: Upload jar file
      uses: actions/upload-artifact@v3
      with:
        name: target-file
        path: ${{ github.workspace }}/${{ env.API_GATEWAY_JAR }} 

  deploy: 
    needs:
    - build
    runs-on: ubuntu-latest      
    steps:
    - name: Login with Service SP
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Get Inactive Side Name"
      id: show-inactive-side     
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az extension add --name spring
          name=$(az spring app deployment list --app ${{ env.API_GATEWAY }} -s ${{ env.SPRING_APPS_SERVICE }} -g ${{ env.RESOURCE_GROUP }} --query "[?properties.active == \`false\`].name" --output tsv)
          echo "deployment-name=$name"
          echo "deployment-name=$name" >> $GITHUB_OUTPUT
